#!/bin/bash
##PBS -N compcf_tophat22_n10_nbar3e-4
#PBS -N compcf_bao
#PBS -l walltime=72:00:00
#PBS -l nodes=1:ppn=2
#PBS -m ae
#PBS -j oe

#ssh ksf293@sirocco.cosmo.fas.nyu.edu /opt/torque/bin/qsub .
cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR
echo 'starting'
echo -n 'Job is running on node '; cat $PBS_NODEFILE
#python lognormal.py
source /home/users/ksf293/miniconda3/etc/profile.d/conda.sh
conda activate nbodykit3
python compute_cf.py
#python lognormal.py
echo 'done'
