#!/bin/bash
#PBS -N tophat_3e-4_10-100
#PBS -l walltime=72:00:00
#PBS -l nodes=1:ppn=24
#PBS -m ae
#PBS -j oe

#ssh ksf293@sirocco.cosmo.fas.nyu.edu /opt/torque/bin/qsub .
cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR
echo 'starting'
echo -n 'Job is running on node '; cat $PBS_NODEFILE
#python lognormal.py
source /home/users/ksf293/miniconda3/etc/profile.d/conda.sh
conda activate nbodykit3
#python bao_iterative.py
python compute_cf.py
#python lognormal.py
echo 'done'
